"""empty message

Revision ID: 15d1b089ecfe
Revises: 764ba0492a75
Create Date: 2020-10-04 22:07:10.964815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d1b089ecfe'
down_revision = '764ba0492a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payees', type_='foreignkey')
    op.drop_column('payees', 'user_id')
    # ### end Alembic commands ###
