"""empty message

Revision ID: 59c0ef87d354
Revises: 15d1b089ecfe
Create Date: 2020-10-04 22:09:07.813975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c0ef87d354'
down_revision = '15d1b089ecfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'payees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payees', type_='foreignkey')
    # ### end Alembic commands ###
